//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummerCamp.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionTables
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompetitionTables()
        {
            this.StudentsTables = new HashSet<StudentsTables>();
        }
    
        public string NameCompetition { get; set; }
        public string StatusCompetition { get; set; }
    
        public virtual StatusTables StatusTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsTables> StudentsTables { get; set; }
    }
}
