//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummerCamp.ModelFolder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SummerCampDataBaseEntities : DbContext
    {
        public SummerCampDataBaseEntities()
            : base("name=SummerCampDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompetitionTables> CompetitionTables { get; set; }
        public virtual DbSet<GroupTables> GroupTables { get; set; }
        public virtual DbSet<PhotoPageTable> PhotoPageTable { get; set; }
        public virtual DbSet<SpecializationTable> SpecializationTable { get; set; }
        public virtual DbSet<StatusTables> StatusTables { get; set; }
        public virtual DbSet<StudentsTables> StudentsTables { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
