//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummerCamp.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoPageTable
    {
        public string NamePhoto { get; set; }
        public byte[] Photo { get; set; }
    }
}
