//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummerCamp.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsTables
    {
        public int PersonalNumberStudents { get; set; }
        public string SurnameStudents { get; set; }
        public string NameStudents { get; set; }
        public string MiddleName { get; set; }
        public string NameGroup { get; set; }
        public string NameCompetition { get; set; }
        public decimal Scores { get; set; }
    
        public virtual CompetitionTables CompetitionTables { get; set; }
        public virtual GroupTables GroupTables { get; set; }
    }
}
